version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
      - echo Installing Gulp
      - npm install -g gulp
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
  post_build:
    commands:
      - echo Build completed on `date`
  artifacts:
    files:
      - app.js
      - gulpfile.js
      - package.json
      - controllers/*
      - models/*
      - Routes/*